file_read = open('file operation1.txt','r')
print(file_read.read())
file_read.close()
file_write = open('file operation1.txt','w')
file_write.write("harshit like coding")
file_write.close()
file_read = open('file operation1.txt','r')
print(file_read.read())
file_read.close()
file_write = open('file operation1.txt','a')
file_write.write("harshit is learning coding from codingal")
file_write.close()
file_read = open('file operation1.txt','r')
print(file_read.read())
file_read.close()