from tkinter import *
window = Tk()
window.title('tkinter sample window')
window.geometry('300x300')
greeting = Label(text= "Hello user", fg= 'black',bg= 'white')
Button = Button(text= "click me ", bg= 'black', fg= 'white')
Entry = Entry(fg= "yellow",bg="blue",width= 50)
greeting.pack()
Button.pack()
Entry.pack()
Frame = Frame(master=window,relief= RAISED,borderwidth= 5)
Frame.pack()
Label = Label(master=Frame, text= 'Sample Frame')
Label.pack()
Textbox = Text(fg= 'green',bg='yellow')
Textbox.pack()
window.mainloop()